{ pkgs, ... }:

/*
 * This file has been generated by autoport.
 * **Do not** open a Pull Request without having verified the port works.
 */
{
  mobile.device.name = "lge-hammerhead";
  mobile.device.identity = {
    name = "Nexus 5";
    manufacturer = "LGE";
  };

  mobile.hardware = {
    soc = "qualcomm-msm8974";
    ram = 1024 * 0/* (in MB) To be filled by the user */;
    screen = {
      width = 0/* To be filled by the user */; height = 0/* To be filled by the user */;
    };
  };

  mobile.boot.stage-1 = {
    kernel.package = pkgs.callPackage ./kernel { };
  };

  mobile.system.android = {

    bootimg.flash = {
      offset_base = "0x00000000";
      offset_kernel = "0x00008000";
      offset_ramdisk = "0x02900000";
      offset_second = "0x00f00000";
      offset_tags = "0x02700000";
      pagesize = "2048";
    };
  };

  boot.kernelParams = [
    # Extracted from an Android boot image
    "console=ttyHSL0,115200,n8"
    "androidboot.hardware=hammerhead"
    "user_debug=31"
    "maxcpus=2"
    "msm_watchdog_v2.enable=1"
  ];

  mobile.system.type = "android";

  /* The usb mode could not be detected.
   * Assuming this is an older device, android_usb should be used.
   * For a newer device, gadgetfs is to be used.
   */
  mobile.usb.mode = null;

  /* To be changed by the author, though those may or may work with any device. */
  # Google
  mobile.usb.idVendor = "18D1";
  # "Nexus 4"
  mobile.usb.idProduct = "D001";

}
